#############################################################################
# Makefile for building: BasicViewer
# Generated by qmake (2.01a) (Qt 4.7.2) on: Thu May 5 20:32:31 2011
# Project:  BasicViewer.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/QT/QtCreator/share/qtcreator/qml/qmljsdebugger -o Makefile BasicViewer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wno-non-virtual-dtor -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I. -Iui -I/usr/include -I/usr/local/include -I/usr/X11R6/include -Imoc -Iui
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = glbox.cpp \
		main.cpp \
		MainWindow.cpp moc/moc_glbox.cpp \
		moc/moc_MainWindow.cpp
OBJECTS       = obj/glbox.o \
		obj/main.o \
		obj/MainWindow.o \
		obj/moc_glbox.o \
		obj/moc_MainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		BasicViewer.pro
QMAKE_TARGET  = BasicViewer
DESTDIR       = 
TARGET        = BasicViewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/ui_MainWindowBase.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BasicViewer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/QT/QtCreator/share/qtcreator/qml/qmljsdebugger -o Makefile BasicViewer.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/QT/QtCreator/share/qtcreator/qml/qmljsdebugger -o Makefile BasicViewer.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/BasicViewer1.0.0 || $(MKDIR) obj/BasicViewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/BasicViewer1.0.0/ && $(COPY_FILE) --parents glbox.h MainWindow.h Color.h Point2D.h vector.h matrix.h obj/BasicViewer1.0.0/ && $(COPY_FILE) --parents glbox.cpp main.cpp MainWindow.cpp obj/BasicViewer1.0.0/ && $(COPY_FILE) --parents ui/MainWindowBase.ui obj/BasicViewer1.0.0/ && (cd `dirname obj/BasicViewer1.0.0` && $(TAR) BasicViewer1.0.0.tar BasicViewer1.0.0 && $(COMPRESS) BasicViewer1.0.0.tar) && $(MOVE) `dirname obj/BasicViewer1.0.0`/BasicViewer1.0.0.tar.gz . && $(DEL_FILE) -r obj/BasicViewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_glbox.cpp moc/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_glbox.cpp moc/moc_MainWindow.cpp
moc/moc_glbox.cpp: Color.h \
		Point2D.h \
		matrix.h \
		vector.h \
		glbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) glbox.h -o moc/moc_glbox.cpp

moc/moc_MainWindow.cpp: ui/ui_MainWindowBase.h \
		glbox.h \
		Color.h \
		Point2D.h \
		matrix.h \
		vector.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc/moc_MainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_MainWindowBase.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_MainWindowBase.h
ui/ui_MainWindowBase.h: ui/MainWindowBase.ui
	/usr/bin/uic-qt4 ui/MainWindowBase.ui -o ui/ui_MainWindowBase.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/glbox.o: glbox.cpp glbox.h \
		Color.h \
		Point2D.h \
		matrix.h \
		vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/glbox.o glbox.cpp

obj/main.o: main.cpp MainWindow.h \
		ui/ui_MainWindowBase.h \
		glbox.h \
		Color.h \
		Point2D.h \
		matrix.h \
		vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/MainWindow.o: MainWindow.cpp MainWindow.h \
		ui/ui_MainWindowBase.h \
		glbox.h \
		Color.h \
		Point2D.h \
		matrix.h \
		vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o MainWindow.cpp

obj/moc_glbox.o: moc/moc_glbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_glbox.o moc/moc_glbox.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

